name: learn-github-actions
on: [workflow_call]
jobs:
  ci-server:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Lint Code
      - run: echo OK
        name: unit test
      - run: echo OK
        name: integration test
      - run: echo OK
        name: code Review
      - run: echo OK
        name: Release Software
      - run: env
        name: env variables
      - run: ls -ltr
        name: list all files