name: learn-github-actions
on: [workflow_call]
jobs:
  ci-server-1:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Lint Code
      - run: echo OK
        name: unit test
      - run: echo OK
        name: integration test
      - run: /opt/sonar-scanner-7.1.0.4889-linux-x64/bin -Dsonar.host.url=http://sonarqube-internal.pdevops78.online:9000 -Dsonar.projectKey=expense-backend -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin123
        name: code Review
      - run: echo OK
        name: Release Software
      - run: npm install
        name: install mode modules



#  /opt/sonar-scanner-7.1.0.4889-linux-x64/bin -Dsonar.host.url=http://sonarqube-internal.pdevops78.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true -Dsonar.login=${{ steps.vault-secrets.outputs.sonarqube_user }} -Dsonar.password=${{ steps.vault-secrets.outputs.sonarqube_password }}