name: learn-github-actions
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true
        type: string
jobs:
  ci-server:
    runs-on: [self-hosted]
    steps:
      - name: Get Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.pdevops78.online:8200
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/github_actions sonarqube_user | sonarqube_user ;
            common/data/github_actions sonarqube_password | sonarqube_password ;
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Lint Code
      - run: echo OK
        name: unit test
      - run: echo OK
        name: integration test
      - run: /opt/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://3.88.166.118:9000 -Dsonar.projectKey=${{inputs.project_name }} -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin123
        name: code Review
      - run: echo OK
        name: Release Software





#  /opt/sonar-scanner-7.1.0.4889-linux-x64/bin -Dsonar.host.url=http://sonarqube-internal.pdevops78.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true -Dsonar.login=${{ steps.vault-secrets.outputs.sonarqube_user }} -Dsonar.password=${{ steps.vault-secrets.outputs.sonarqube_password }}