name: learn-github-actions
on:
  workflow_call:
    inputs:
      sonar_login:
        required: true
        type: string
      sonar_password:
        required: true
        type: string
      project_name:
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: code build
      - run: echo OK
        name: code test
      - run: /opt/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://172.31.91.23:9000 -Dsonar.login=${{inputs.sonar_login}} -Dsonar.password=${{inputs.sonar_password}} -Dsonar.projectKey=${{inputs.project_name}}
        name: code Review


