name: learn-github-actions
on:
  workflow_call:
    inputs:
      sonar_login:
        required: true
        type: string
      sonar_password:
        required: true
        type: string
      project_name:
        required: true
        type: string
      npm_install:
        type: boolean

jobs:
  job1:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Lint Code
      - run: echo OK
        name: unit test
      - run: echo OK
        name: integration test

      - run: Install nodejs
        name: dnf install nodejs -y
      - run: Install dependencies
        if: ${{ inputs.npm_install }}
        name: npm install
      - run: /opt/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://172.31.33.218:9000 -Dsonar.login=${{inputs.sonar_login}} -Dsonar.password=${{inputs.sonar_password}} -Dsonar.projectKey=${{inputs.project_name}}
        name: code Review
      - run: env
        name: env
      - run: echo OK
        name: code release





